FIX: Could not set field value [NAO_PODE] value by reflection
Stack Trace:  
	java.lang.RuntimeException: Não foi possível calcular acesso ao serviço SIGA;FE;ARMAZ:Armazenamento de Arquivos;ARMAZ_ESTAT:Estatística de Armazenamento
	at br.gov.jfrj.siga.cp.bl.CpConfiguracaoBL.podeUtilizarServicoPorConfiguracao(CpConfiguracaoBL.java:795)
	at br.gov.jfrj.siga.api.v1.NotificacoesGet.run(NotificacoesGet.java:35)
	at com.crivano.swaggerservlet.SwaggerServlet.run(SwaggerServlet.java:617)
	at com.crivano.swaggerservlet.SwaggerServlet.doPost(SwaggerServlet.java:372)
	at com.crivano.swaggerservlet.SwaggerServlet.doGet(SwaggerServlet.java:326)
Caused by: javax.persistence.PersistenceException: org.hibernate.PropertyAccessException: Could not set field value [NAO_PODE] value by reflection : [class br.gov.jfrj.siga.cp.CpTipoServico.situacaoDefault] setter of br.gov.jfrj.siga.cp.CpTipoServico.situacaoDefault
	at br.gov.jfrj.siga.model.dao.ModeloDao.consultar(ModeloDao.java:92)
	at br.gov.jfrj.siga.cp.bl.CpConfiguracaoBL.podeUtilizarServicoPorConfiguracao(CpConfiguracaoBL.java:779)
Caused by: org.hibernate.PropertyAccessException: Could not set field value [NAO_PODE] value by reflection : [class br.gov.jfrj.siga.cp.CpTipoServico.situacaoDefault] setter of br.gov.jfrj.siga.cp.CpTipoServico.situacaoDefault
Caused by: java.lang.IllegalArgumentException: Can not set br.gov.jfrj.siga.cp.model.enm.CpSituacaoDeConfiguracaoEnum field br.gov.jfrj.siga.cp.AbstractCpTipoServico.situacaoDefault to null value





Quando é criado o CpServico a partir de uma nova chave, se o Cache da CpTipoServico é iniciado pela ExDAO a CpDAO não consegue consultar e carregar a CpTipoServico do cache com a chamada (Vice-Versa)

CpTipoServico tpsrv = dao().consultar(CpTipoServico.TIPO_CONFIG_SISTEMA, CpTipoServico.class,false);

Foi necessário retirar a estratégia de concorrência de escrita do cache para permitir que ambas as instâncias da DAO consiga carregar a classe.